### ISSUE TITLE
希望能加一个运行一段时间（最好可以自己设定时间）快手后重新启动快手，因为长时间运行快手后，手机会显示快手已经停止运行导致识别错误。

### ISSUE THREAD

**Issue by NyaNyaHua4290** [binklings/AutoBKLS#1]

**Comment by binklings** [comment]
如果在刷视频时快手卡死或闪退,会提示找不到目标或验证失败,然后会尝试重启快手的,但是如果快手没有完全崩溃,launchapp就不会起到作用,需要先结束快手进程,而这通常涉及的系统权限问题,需要shizuku或root权限,如果问题持续,我会在未来版本尝试修复

**Comment by NyaNyaHua4290** [comment]
> 如果在刷视频时快手卡死或闪退,会提示找不到目标或验证失败,然后会尝试重启快手的,但是如果快手没有完全崩溃,launchapp就不会起到作用,需要先结束快手进程,而这通常涉及的系统权限问题,需要shizuku或root权限,如果问题持续,我会在未来版本尝试修复

可是这个软件不是已经申请了root权限了吗？。![1692369479725.jpg](https://github.com/binklings/AutoBKLS/assets/74782007/11fc9eeb-7d83-4972-acfa-dea73f3a7944)
